---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: appserver-upddistr-secret
  namespace: protheus-devops
spec:
  encryptedData:
    UPD_PASSWORD: AgAgYk0WPr3gvnVACpVvN7K3wpJAA10lUf2KEA0P+84H24s1xMGIOGvpv1Vw63I4Z/oA5pgoNRgbYb37Zg7lGE9DkRzf1obD89Y4Sf+asRMWYwG9o+ahct/mF/Mw4+wgU7Ia0Ev0lOBqF/elp92OrgElyL5yhA0JdiVPsA1z9opPn5ziLWFHISTrO0iuoo/LgIPVQOmMVDcioOgkweqbIoGbMs1AcJyFMzR5scrxEzMdtOvPIZlSRkVzm1aHXpjU8i5F+WDzzc0J4u+eOVXqRiYILMIcwZe4a7lhbfSeRFDuXx1Gj9b86fHREUHaTENZ9eV2Pwst6fWOPhxzHvLH5suFmP/iBHuwkMwB5PSDFVxvSRNEvcGEbRwe7/CzDt6gGtR0lGPENrL46u4/ahDkGfZOxoQsUIbI1zDubP6fu4Ep1/KsEkzlQdx+EgccyC1pGUy3NYR5BdSdgHUqtLVl467aG0TuHZpl9hOVBRnROtp+9s6viwukQO21pdfTif2eOiMP2COqXeeh1BU0lDhTknUd11hJE8zH79MT65ll+e4nA3P0OnyWb2567F154N6WL619yd9q3ldQ9sUWE9UlbfZEO8yoXz22ma904ZAmvq7kvDiR54NjCVdazkeQQXxI6Tgv0x79S555db14MPmsmcYR1Eq6cAnEwCv4ecMtD1FKaSq/zMpu8hmTS2cNIrQwiaUqMFScDzBq2951gyCs
  template:
    metadata:
      name: appserver-upddistr-secret
      namespace: protheus-devops
