apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - dbaccess.yaml

# Gerador dinâmico de ConfigMaps (variáveis comuns)
configMapGenerator:
  - name: postgres-config
    namespace: protheus-devops
    envs:
      - postgres.env

# Gerador dinâmico de Secrets (senhas criptografadas em base64)
secretGenerator:
  - name: postgres-secret
    namespace: protheus-devops
    envs:
      - postgres-secret.env