---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: manager-secret
  namespace: protheus-devops
spec:
  encryptedData:
    MANAGER_API_TOKEN: AgARfbgD6e0s+QgzH0JrwhEIamqYp+mNx5kAUQfUbBfFKK53GIh7n+W7tgAJa+6m9zFSerJZyZAoDAHaUhb+w1ubGnJ/Cxbwy7y4QrZvl7xSBWTByAi90OKzmunagAxJjm9QtSyhtHifePStQVdE+h7GV8TzqtwozZXhosF+bxHcPsFtyMf+CLI2Qk8Z90mX/oZah7mDkxoBNEqeGW6Xk5VuUe7WyAVVY/IRigsPpKmKrNLEGq9oP+6W/whucMDyhq3w292Z6GuZ1hssOoHgFOITRND/jJY9bRhfcV2TmeEg2kojpUTclizzfmGmQb1tQSQ/OT5xkAqPx1k4cAMzSSOxtKMvQoiN+lpTjPvtwWFyclYFP/obdLYR9xpdKxl2Zq2OIIueqoWC0VgPb6S+79xc+KSxhT2wJu8PLRdzHA3kpvFAYrSrHxpD2EfKdwFbPY6ignU14tybMMCM+py9p6jwLid/BDVjQT8Gh822pu1k9o+ywKcOnT9CsqXv2HenP/6nEz7GnAjNTPWbdXAVe8zTLKPaLnSig6gUaSucsXbR3bP3cm8H3xtoYMeEWP91wELceeKr8tf5UU+5kINUBg/+y1OE9kk1e6W3Zae5H02VczC9YLTEEbMDRWBXDumFGiJVoSrkzvv3cXiXniOcCgevMf7JFU4UqnVxrCNf3XUuHIL1ZoP9MWcLpEkQi6IF2Oijzn/E9zB3iAuSrHPA5oKU7Ebr/ibPSmuaffLS9vKpWZMcIK/azRJ1XtLfMWOwHPM8uBoJ3ItiA22fOSdqv8A9
  template:
    metadata:
      name: manager-secret
      namespace: protheus-devops
