---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: protheus-devops
spec:
  encryptedData:
    DB_PASSWORD: AgBe5GHNdK84Qs34URS1JKpNS06IY6vyMznPGeI7nB5HRLDbguMA2DLITGAE5x29E5gxsHuGSCDLTN0Lj7QbxyOWKxR+oRjgn6UtRk/5QcDHHNWQWwr1QmIb9nsKnVEXWsHasz5QJ0UyK2Kj7eXlJCpUFGywtI44hZYTF4Ld+IzxiCU1J4bPswb9G5siVOYtXii4ofjy2FgSmSdWDfdaKUtDwbUyYUiEw7o9An0Zp6PzAGq9A//jJm9JByd11M+VBTPs8wa35KeU4kjunp1FqkfylxxhpN+afC+i/9vodaXoHjRvCC/OgoKHeAoKEmahUf2zlITKtNW6W9XWdrvSQIUklNbJS+OYbwmgbzAkgHDEfvI/UWwmb4SKQnXdcf+p2gE36qwRhE2b2n8aViwm5J0RBFM4+1Bcv4ltzvR52wrO6tnWVYHYRrPLjjdY9xLIEDwSTIy2Piq+xOi/GybSXRjscdZvKWkxdZpLZ5p+5OlL+CCB/4Woq0242oIgrZk5AxWOkM46Ba2EreAyf8PhACCd2LHPlOsMjG5KwshIYmjD+SdGrG+YZEGWYgpyffPR+lzuaDjVzHGI/6ynLqNHE0BucXDB+xy35M7vXUqMqNuFbnDdLUsr2g/MunlXEPFZsOdv0Iw5SQ59VUgBy0VRQeZtHwAgR8YGzMTq9g3Hl0ksaKcr53pUrzKUx20vfLneZ3JQk8s8Sg1l/ZhbnHIszrk=
    POSTGRES_PASSWORD: AgBaERNSKbW8pZHPNrSXnSjLq2JTEsebzXbUzlsU/2iFKP22lBdpJLF2aDMF07oPw6FpneVaSBnKYwfV+AnJ/RJqrJFCu+vn+GsGCDiN1ovI6M4RBxtssAGmVQUNWulTi7BmAoBtGFJ/5haLigEGd71srIiUvE0yuYPwgXpzDdxMuct65Zm8pYyatL4VScotx/T74RzRDx++DTEUolk13niNU6drAEOgs2yyzk4s/QwONLc4/TNisqz9j0SDQkiRNOdfMx0fppcyqjlq5DO9/bIB186fTiSoL9CF/IvhL6i5TJNlbcSmsYK5y9dhYel3Bw4zeizD5yg3QFhwIB+bFf9vuxhtSDdUiQehpaV9G90LDGsw+lzg6oD+iaoET4Ej0bOJVv1R5oU9ckH5zXQBgVa3EfuPjeAZcILxBbjKD0l6QwVWbHEZNkXycDAENqu4XH4do+U3bjqOh9TI8Was4JRRo+p8Tcudg5uFbAMDYSfS6FiXy9IjGK0LlAROAfxWObGsYTenjTUSTfuN86C78XofmPglmHxaQRsysmyzUop5AvaE4OJ8QX4KTkDYkoCLQxOChoifjo+raOo9ZjsfVipLvpqWsuISixSZtq+93bwwOOCp9+bzBmljnuNLTLk3SliU9LbGmG5pZqnDewxu0HONXk9XjEgLwzGomHf70RwuoOGvOJTZvgVbHvFs8PrV6h99ZCMyo3xtPWY1YGCzqBE=
  template:
    metadata:
      name: postgres-secret
      namespace: protheus-devops
